export const energy_cn = {
  systemEnergy: "系统能耗",
  totleCharge: "总充电量",
  totleDischarge: "总放电量",
  dailyCharge: "日充电量",
  dailyDischarge: "日放电量",
  chargTitle_ele: "日充放电量",
  chargTitle_power: "功率曲线",
  chargTitle_energy: "能耗排行",
  Ri_Chong: "日充",
  Ri_Fang: "日放",
  BMS_Power: "BMS功率",
  PCS_Power: "PCS功率",
  unit: "单位",
  cancel: "取消",
  popup_title: "选择日期",
  confirm: "确定",
};
export const energy_en = {
  systemEnergy: "System energy",
  totleCharge: "Total charge",
  totleDischarge: "Totle Discharge",
  dailyCharge: "Daily Charge",
  dailyDischarge: "Daily discharge",
  chargTitle_ele: "Daily charge and discharge",
  chargTitle_power: "Power curve",
  chargTitle_energy: "Energy consumption ranking",
  Ri_Chong: "Daily Charge",
  Ri_Fang: "Daily Discharge",
  BMS_Power: "BMS Power",
  PCS_Power: "PCS Power",
  unit: "Unit",
  cancel: "Cancel",
  popup_title: "Choose Date",
  confirm: "Confirm",
};
