export const income_cn = {
  timePrice: "分时电价",
  Jtext: "尖",
  Ftext: "峰",
  Ptext: "平",
  Gtext: "谷",
  Cost: "成本",
  system_profits: "系统收益",
  Title1: "总收益",
  Title2: "日收益",
  Title3: "尖收益",
  Title4: "峰收益",
  Title5: "平收益",
  Title6: "谷收益",
  totleCount: "收益统计",
  cancel: "取消",
  popup_title: "选择日期",
  confirm: "确定",
};
export const income_en = {
  timePrice: "Time Of Price",
  Jtext: "J-Price",
  Ftext: "F-Price",
  Ptext: "P-Price",
  Gtext: "G-Price",
  Cost: "Cost",
  system_profits: "System Profits",
  Title1: "Total Income",
  Title2: "Daily Income",
  Title3: "Top Income",
  Title4: "Peak Income",
  Title5: "Flat Income",
  Title6: "Valley Income",
  totleCount: "Income statistics",
  cancel: "Cancel",
  popup_title: "Choose Date",
  confirm: "Confirm",
};
