export const station_cn = {
  chartTitle: "系统运行占比",
  system: "系统",
  income: "收益",
  equipment: "设备",
  energy: "能耗",
  charge: "充电",
  disCharge: "放电",
  standby: "待机",
  failure: "故障",
  shutDown: "离网",
  cancel: "取消",
  confirm: "确定",
};
export const station_en = {
  chartTitle: "Proportion Of System Operation",
  system: "System",
  income: "Income",
  equipment: "Equipment",
  energy: "Energy",
  charge: "Charging",
  disCharge: "Discharge",
  standby: "Standby",
  failure: "Failure",
  shutDown: "Off-Grid",
  cancel: "Cancel",
  confirm: "Confirm",
};
