export const systemPage_cn = {
    myPopTitle:"选择系统",
    sysRunStateTitle:"系统运行情况",
    maxSingleV:"最大单体电压",
    minSingleV:"最小单体电压",
    soh:"SOH",
    wet:"湿度",
    maxSingleT:"最大单体温度",
    minSingleT:"最小单体温度",
    power:"功率",
    tem:"温度",
    voltage:"电压",
    current:"电流",
    systemTitle1:"系统",
    systemTitle2:"簇",
    systemTitle3:"单体",
    systemPcsTitle:"PCS",
    systemPowerTitle:"功率曲线",
    systemChargeTitle:"充放电量",
    systemPcsDC:"PCS直流侧",
    systemPcsAC:"PCS交流侧",
    systemDcCurrent:"电流",
    systemDcVol:"电压",
    systemDcPower:"总功率",
    systemDcFrequency:"交流频率",
    systemDcFactor:"功率因数",
    systemCharge:"充电",
    systemDisCharge:"放电",
  };
  export const systemPage_en={
    myPopTitle:"Select System",
    sysRunStateTitle:"System Run State",
    maxSingleV:"Max V",
    minSingleV:"Min V",
    soh:"SOH",
    wet:"Humidity",
    maxSingleT:"Max T",
    minSingleT:"Min T",
    power:"Power",
    tem:"Temperature",
    voltage:"Voltage",
    current:"Current",
    systemTitle1:"System",
    systemTitle2:"Cluster",
    systemTitle3:"Cell",
    systemPcsTitle:"PCS",
    systemPowerTitle:"Power Curve",
    systemChargeTitle:"Capacity",
    systemPcsDC:"PCS-DC",
    systemPcsAC:"PCS-AC",
    systemDcCurrent:"Current",
    systemDcVol:"Voltage",
    systemDcPower:"Power",
    systemDcFrequency:"Frequency",
    systemDcFactor:"Factor",
    systemCharge:"Charge",
    systemDisCharge:"DisCharge",
  };