export const systemPage_cn = {
  myPopTitle: "选择系统",
  sysRunStateTitle: "系统运行情况",
  maxSingleV: "最大单体电压",
  maxSingleVP: "最大电压位置",
  minSingleV: "最小单体电压",
  minSingleVP: "最小电压位置",
  soh: "SOH",
  wet: "湿度",
  maxSingleT: "最大单体温度",
  maxSingleTP: "最大温度位置",
  minSingleT: "最小单体温度",
  minSingleTP: "最小温度位置",
  power: "功率",
  tem: "温度",
  voltage: "电压",
  current: "电流",
  systemTitle1: "系统",
  systemTitle2: "簇",
  systemTitle3: "单体",
  systemPcsTitle: "PCS",
  systemPowerTitle: "功率曲线",
  systemChargeTitle: "充放电量",
  systemPcsDC: "PCS直流侧",
  systemPcsAC: "PCS交流侧",
  systemDcCurrent: "电流",
  systemDcVol: "电压",
  systemDcPower: "总功率",
  systemDcFrequency: "交流频率",
  systemDcFactor: "功率因数",
  systemCharge: "充电",
  systemDisCharge: "放电",
  //pcs
  pcs_state: "状态",
  pcs_ApparentPower: "视在功率",
  pcs_BranchPower_01: "分支1",
  pcs_BranchPower_02: "分支2",
  pcs_BranchPower_03: "分支3",
  pcs_BranchPower_04: "分支4",
  pcs_BranchPower_05: "分支5",
  pcs_BranchPower_06: "分支6",
  pcs_BranchPower_07: "分支7",
  pcs_BranchPower_08: "分支8",
  pcs_BranchPower_09: "分支9",
  pcs_BranchPower_10: "分支10",
  pcs_BranchPower_11: "分支11",
  pcs_BranchPower_12: "分支12",
  pcs_BranchPower_13: "分支13",
  pcs_BranchPower_14: "分支14",
  pcs_BranchPower_15: "分支15",
  pcs_BranchPower_16: "分支16",
  pcs_BranchPower_17: "分支17",
  pcs_BranchPower_18: "分支18",
  pcs_BranchPower_19: "分支19",
  pcs_BranchPower_20: "分支20",
  pcs_Dc: "直流侧电流",
  pcs_Dp: "直流侧功率",
  pcs_Dv: "直流侧电压",
  pcs_Frequency: "频率",
  pcs_Ia: "Ia",
  pcs_Ib: "Ib",
  pcs_Ic: "Ic",
  pcs_Id: "Id",
  pcs_ModuleTemp: "模块温度",
  pcs_NetStatus: "工作模式",
  pcs_OccurTime: "数据采集时间",
  pcs_Power: "功率",
  pcs_PowerFactor: "功率因数",
  pcs_RunState: "运行模式",
  pcs_SwitchStatus: "开关模式",
  pcs_SystemState: "系统状态",
  pcs_Temp: "温度",
  pcs_TodayChargeEnergy: "今日充电量",
  pcs_TodayDisChargeEnergy: "今日放电量",
  pcs_TotalChargeEnergy: "总充电量",
  pcs_TotalDisChargeEnergy: "总放电量",
  pcs_TotalUnUseEnergy: "累计无功电量",
  pcs_Ua: "Ua",
  pcs_Ub: "Ub",
  pcs_Uc: "Uc",
  pcs_UnPower: "无功功率",
  pcs_Warn: "警告内容",
  //cluster
  cluster_chartTitle: "簇SOC",
  cluster_chartTitle1: "簇一致性",
  cluster_voltageCons:"簇电压一致性",
  cluster_powerCons:"簇功率一致性",
  cluster_voltageDifCons:"簇压差一致性",
  cluster_temDifCons:"簇温度差一致性",
  cluster_name:"簇",
  //采温点
  volSimpleTitle:"采压点",
  temSimpleTitle:"采温点"
};
export const systemPage_en = {
  myPopTitle: "Select System",
  sysRunStateTitle: "System Run State",
  maxSingleV: "Max V",
  maxSingleVP: "Max-V-P",
  minSingleV: "Min V",
  minSingleVP: "Min-V-P",
  soh: "SOH",
  wet: "Humidity",
  maxSingleT: "Max T",
  maxSingleTP: "Max-T-P",
  minSingleT: "Min T",
  minSingleTP: "Min-T-P",
  power: "Power",
  tem: "Temperature",
  voltage: "Voltage",
  current: "Current",
  systemTitle1: "System",
  systemTitle2: "Cluster",
  systemTitle3: "Cell",
  systemPcsTitle: "PCS",
  systemPowerTitle: "Power Curve",
  systemChargeTitle: "Capacity",
  systemPcsDC: "PCS-DC",
  systemPcsAC: "PCS-AC",
  systemDcCurrent: "Current",
  systemDcVol: "Voltage",
  systemDcPower: "Power",
  systemDcFrequency: "Frequency",
  systemDcFactor: "Factor",
  systemCharge: "Charge",
  systemDisCharge: "DisCharge",
  //pcs
  pcs_state: "state",
  pcs_ApparentPower: "ApparentPower",
  pcs_BranchPower_01: "BranchPower_01",
  pcs_BranchPower_02: "BranchPower_02",
  pcs_BranchPower_03: "BranchPower_03",
  pcs_BranchPower_04: "BranchPower_04",
  pcs_BranchPower_05: "BranchPower_05",
  pcs_BranchPower_06: "BranchPower_06",
  pcs_BranchPower_07: "BranchPower_07",
  pcs_BranchPower_08: "BranchPower_08",
  pcs_BranchPower_09: "BranchPower_09",
  pcs_BranchPower_10: "BranchPower_10",
  pcs_BranchPower_11: "BranchPower_11",
  pcs_BranchPower_12: "BranchPower_12",
  pcs_BranchPower_13: "BranchPower_13",
  pcs_BranchPower_14: "BranchPower_14",
  pcs_BranchPower_15: "BranchPower_15",
  pcs_BranchPower_16: "BranchPower_16",
  pcs_BranchPower_17: "BranchPower_17",
  pcs_BranchPower_18: "BranchPower_18",
  pcs_BranchPower_19: "BranchPower_19",
  pcs_BranchPower_20: "BranchPower_20",
  pcs_Dc: "Dc",
  pcs_Dp: "Dp",
  pcs_Dv: "Dv",
  pcs_Frequency: "Frequency",
  pcs_Ia: "Ia",
  pcs_Ib: "Ib",
  pcs_Ic: "Ic",
  pcs_Id: "Id",
  pcs_ModuleTemp: "ModuleTemp",
  pcs_NetStatus: "NetStatus",
  pcs_OccurTime: "OccurTime",
  pcs_Power: "Power",
  pcs_PowerFactor: "PowerFactor",
  pcs_RunState: "RunState",
  pcs_SwitchStatus: "SwitchStatus",
  pcs_SystemState: "SystemState",
  pcs_Temp: "Temp",
  pcs_TodayChargeEnergy: "TodayChargeEnergy",
  pcs_TodayDisChargeEnergy: "TodayDisChargeEnergy",
  pcs_TotalChargeEnergy: "TotalChargeEnergy",
  pcs_TotalDisChargeEnergy: "TotalDisChargeEnergy",
  pcs_TotalUnUseEnergy: "TotalUnUseEnergy",
  pcs_Ua: "Ua",
  pcs_Ub: "Ub",
  pcs_Uc: "Uc",
  pcs_UnPower: "UnPower",
  pcs_Warn: "Warn",
  //cluster
  cluster_chartTitle: "SOC",
  cluster_chartTitle1: "Consistency",
  cluster_voltageCons:"voltage consistency",
  cluster_powerCons:"power consistency",
  cluster_voltageDifCons:"voltage difference consistency",
  cluster_temDifCons:"temperature difference consistency",
  cluster_name:"Cluster",
    //采温点
    volSimpleTitle:"pressure point",
    temSimpleTitle:"temperature point"
};