export const menus_cn = {
  footer: ["电站总览", "总事件", "历史数据", "我的"],
};
export const menus_en={
  footer: ["Plant Overview", "Total event", "Historical data", "Mine"],
};
export const topTitle_cn = { title: "电站总览" };
export const topTitle_en={
  title: "Plant Overview",
};
export const allStation_cn = {
  allCharge: "总收益",
  allDisCharge: "昨日收益",
  sysCount: "系统运行占比",
  stateCharge:"充电",
  stateDisCharge:"放电",
  stateStandby:"待机",
  stateFailure:"故障",
  stateShutDown:"离网",
  tabTitle1:"场站",
  tabTitle2:"收益",
  tabTitle3:"能耗",
  profitTitle1:"储能收益",
  profitTitle2:"光伏收益",
  profitTitle3:"充电桩收益",
  profitEsChart1:"总充电量",
  profitEsChart2:"总放电量",
  profitEsChart3:"总收益",
  profitEsChartYxis:"充电量",
  profitEsChartYxis1:"收益",
  profitUnit:"元",
  esTitle1:"总收益",
  esTitle2:"日收益",
  esTitle3:"尖收益",
  esTitle4:"峰收益",
  esTitle5:"平收益",
  esTitle6:"谷收益",
  esTitle7:"收益统计",
  esChart2lend:"BMS功率",
  esChart2lend1:"PCS功率",
  energyEsTitle:"储能能耗",
  energyTitle1:"总充电量",
  energyTitle2:"总放电量",
  energyEsChartSub1:"日充电量",
  energyEsChartSub2:"日放电量",

  energySubTitle1:"日充放电量",
  energySubTitle2:"功率曲线",
  energySubTitle3:"能耗排行",
  energyPvTitle:"光伏能耗",
  pvChartlend:"功率",
  energyPvSubTitle1:"总放电量",
  energyPvSubTitle2:"日放电量",
  energyPvSubTitle3:"节约减排",
  energyPvSubTitle4:"等效植树",
  energyPvChartTitle:"光伏功率",
  energyCpTitle:"充电桩能耗",
  energyCpSubTitle1:"总充电量",
  energyCpSubTitle2:"日充电量",
  dateDate:"选择日期"
};
export const allStation_en= {
  allCharge: "Total Income",
  allDisCharge: "Yesterday Income",
  sysCount: "System running ratio",
  allCharge: "Total Charge",
  allDisCharge: "Total Discharge",
  sysCount: "System Running Ratio",
  stateCharge:"Charging",
  stateDisCharge:"Discharge",
  stateStandby:"Standby",
  stateFailure:"Failure",
  stateShutDown:"Off-Grid",
  tabTitle1:"Station",
  tabTitle2:"Income",
  tabTitle3:"Energy",
  profitTitle1:"ES Income",
  profitTitle2:"PV Income",
  profitTitle3:"CP Income",
  profitEsChart1:"Total charge",
  profitEsChart2:"Total Discharge",
  profitEsChart3:"Total Income",
  profitEsChartYxis:"Charge Capacity",
  profitEsChartYxis1:"Income",
  profitUnit:"￥",
  esTitle1:"Total Income",
  esTitle2:"Daily Income",
  esTitle3:"Top Income",
  esTitle4:"Peak Income",
  esTitle5:"Flat Income",
  esTitle6:"Valley Income",
  esTitle7:"Income statistics",
  esChart2lend:"BMSPower",
  esChart2lend1:"PCSPower",
  energyEsTitle:"Energy Storage",
  energyTitle1:"Total charge",
  energyTitle2:"Total Discharge",

  energyEsChartSub1:"Daily Charge",
  energyEsChartSub2:"Daily Discharge",

  energySubTitle1:"Daily Charge&Discharge ",
  energySubTitle2:"Power Curve",
  energySubTitle3:"Energy Consumption Ranking",
  energyPvTitle:"PV Consumption",
  pvChartlend:"Power",
  energyPvSubTitle1:"Total Discharge",
  energyPvSubTitle2:"Daily Discharge",
  energyPvSubTitle3:"CO2",
  energyPvSubTitle4:"≈Planting",
  energyPvChartTitle:"PV Power",
  energyCpTitle:"CP Consumption",
  energyCpSubTitle1:"All Charge",
  energyCpSubTitle2:"Daily Charge",
  dateDate:"Choose Date"
};
export const stationType_cn={
  tab1:"全部",
  tab2:"储能调峰",
  tab3:"智能微网",
  tab4:"光伏",
  tab5:"充电桩",
  tab5:"户外柜",
  tab6:"虚拟电厂",
};
export const stationType_en={
  tab1:"All",
  tab2:"Energy storage peaking",
  tab3:"Intelligent microgrid",
  tab4:"Solar power",
  tab5:"Charging pile",
  tab5:"Outdoor cabinet",
  tab6:"Virtual power plant",
}
export const stationData_cn={
  capacity:"装机容量",
  dailyCharge:"今日充电",
  dailyDisCharge:"今日放电",
  power:"当前功率",
  safe:"安全运行",
  day:"天",
  placeText:"请输入电站名称",
  nomore:"没有更多了"
}
export const stationData_en={
  capacity:"Capacity",
  dailyCharge:"Charge",
  dailyDisCharge:"Discharge",
  power:"Power",
  safe:"Safe",
  day:"Day",
  placeText:"Please enter the plant name",
  nomore:"No more"
}
